version: '3.7'

services:

  db:
    ports:
      - 5432:5432
      
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: prosenjit
      POSTGRES_DB: todoapp

volumes:
    db-volume: 